# Generated by Django 5.1.3 on 2024-11-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RacePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in km', max_digits=5)),
                ('elevation', models.DecimalField(decimal_places=2, help_text='Elevation Gain in Meters', max_digits=5)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
