# Generated by Django 5.1.3 on 2024-11-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceposts', '0002_alter_racepost_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racepost',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
